
DROP TYPE IF EXISTS grocery;
CREATE TYPE grocery AS ENUM(
  'Main',
  'Snack',
  'Lunch',
  'Breakfast'
);

CREATE TABLE IF NOT EXISTS shopping_list (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, 
  name text not null, 
  category grocery, 
  price decimal(12,2),
  date_added TIMESTAMP DEFAULT now() not null,
  checked boolean DEFAULT false not null 
  );